// Generated by https://quicktype.io

export interface Neighborhood {
  Name: string;
  Value: string;
}

export interface State {
  Name: string;
  Value: string;
}

export interface Municipality {
  State: string;
  Name: string;
  Value: string;
}

export interface Locality {
  Name: string;
  Value: string;
}

// Generated by https://quicktype.io

export interface Ubication {
  StateCode: string;
  MunicipalityCode: string;
  LocationCode: string;
  Name: string;
  Value: string;
}
